### ISSUE TITLE
when a customer chooses options on the application, the menu scrolls down by itself.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1067]
when a customer chooses options on the application, the menu scrolls down by itself.

https://user-images.githubusercontent.com/83431363/116738888-57cafd00-a9f3-11eb-86cd-5498d8d03f0b.mp4

**Comment by ERAMANrepartos** [comment]
To be more specific - there is an element of the options that tries to scroll from one option to the next when you have made a selection. This is a good idea in principle since a user may not understand they need to scroll down. However, for options where you can pick multiple things inside a single option it means that we are being taken away from the choice we are trying to make. 

This feature should be disabled for options where there are more than a Y/N option
