### ISSUE TITLE
App crashes when viewing any store

### ISSUE THREAD

**Issue by acao** [coopcycle/coopcycle-app#1197]
**Describe the bug**
Hello, love this platform and the federation, great stuff!

When viewing the list of available restaurants via Berlin Khora collective, if I click on any of them, the app crashes.

This issue only began to occur after using the app for a few days. It has persisted for a few months now even after hard restarting the application. I could try reinstalling perhaps?

**To Reproduce**
1. Go to available restaurants
2. Click on a restaurant

**Expected behavior**
Restaurant menu should display

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS 14.6

**Comment by alexsegura** [comment]
Hi 🙂 
Thank you for this bug report. 

I have looked in Sentry, but couldn't find anything where it's 100% sure it's your bug. 

_Maybe_ your problem is this: last week, we wanted to deprecate the kolyma2.com domain name (the former name of Khora), so we configured a HTTP 301 redirect kolyma2.com -> khora.berlin. But the app is not ready to handle a change in domain name. We rolled back the change, but maybe the HTTP layer of the phone has something cached?

What you can try is cleaning the data used by the app. You will need to select a city again, and authenticate again.

**Comment by ERAMANrepartos** [comment]
I'm going to assume this is the issue described above, and close the issue.
