### ISSUE TITLE
Rethink notifications for couriers

### ISSUE THREAD

**Issue by couleurmate** [coopcycle/coopcycle-app#138]
Right now, a notification is sent to couriers when the tasks have changed (i.e. when they have been assigned/unassigned, or reordered). This is a little bit naïve. 

A courier needs to be informed immediately when a critical information about a task has been updated (for example, when the address has changed). 

We need to rethink notifications, to send critical updates in real time.

**Comment by agichim** [comment]
Show more details of each assigned and unassigned task on ‘lock screen’ and ‘notifications drawer’

**New notification**: 

`assigned to` or `unassigned from` `task` or `order` `number`
`pickup location` or `address`

>Assigned to order 344
>Once Across the Garden

>Unassigned from order 344
>Once Across the Garden

>Assigned to task 291
>18 Equality Street, Acomb, YO24 4ES, York, England, United Kingdom

Show a notification for when a task has been modified (a note has been added or a change of address or a tag has been added, etc.)  thanks @couleurmate 

**Changed/updated notification**: 

`task` or  `order` `number` `updated`
`pickup location` or `address`

>Order 344 updated
>Once Across the Garden

>Task 291 updated
>Once Across the Garden

>Task 292 updated
>Once Across the Garden

**Comment by ERAMANrepartos** [comment]
This is a debatable feature. Many people communicate these issues using external communication channels such as Zello for such critical issues. This is because in such a situation, you do not want to rely on a one-way communication with no confirmation. In Zello you know the information has been recieved due to yuor internal comms norms about responses. 

That said, we do need to spend some time thinking about notifications, and scalability.

**Comment by Paul-Eraman-CoopCycle** [comment]
closing, but we are making an epic about this soon
