### ISSUE TITLE
Resuming checkout after clicking on activation link is broken

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#1439]

**Comment by vladimir-8** [comment]
As a quick fix, it seems enough to replace 'CheckoutSummary' with 'CheckoutMoreInfos' in `resumeCheckout` function: https://github.com/coopcycle/coopcycle-app/blob/de5bc383c53c7b754d3d1d4082d5ea9ece970498/src/redux/App/actions.js#L519-L529 I guess navigating to 'CheckoutSummary' does not work, because it's not in the root of `CheckoutNav` navigator. 

I'll try to refactor `CheckoutNav` navigator a bit, so that such manual manipulations are not needed

**Comment by vladimir-8** [comment]
Some issues have been fixed in this PR: https://github.com/coopcycle/coopcycle-app/pull/1530

Issues still open:

- https://github.com/coopcycle/coopcycle-app/issues/1534
