### ISSUE TITLE
The CoopCycle logo appears instead of the kooglof! logo

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1639]
https://github.com/coopcycle/coopcycle-app/assets/77277854/9db32128-8b2e-4a92-b4fe-eb69425710c8

Should be the kooglof logo!

**Comment by r0xsh** [comment]
https://docs.expo.dev/versions/latest/sdk/splash-screen/

**Comment by Perpolita** [comment]
only on iPhones, it's working on Android's phones

**Comment by vladimir-8** [comment]
Will be fixed in https://github.com/coopcycle/coopcycle-app/pull/1672. Updated iOS launch screen to use a solid background color as per Apple guideline https://developer.apple.com/design/human-interface-guidelines/launching#Launch-screens

If we really want to keep the splash screen it should be implemented using a different approach, for example Expo, as suggested by Antoine https://github.com/coopcycle/coopcycle-app/issues/1639#issuecomment-1850463936
