### ISSUE TITLE
Dark mode hides incident list

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1646]
in android 12 phone

can't see incident list in dark mode

![telegram-cloud-photo-size-4-6050668421466669844-y](https://github.com/coopcycle/coopcycle-app/assets/77277854/e38f47f9-89a1-4227-a6a6-b90a192a1a70)

**Comment by vladimir-8** [comment]
It's fixed in https://github.com/coopcycle/coopcycle-app/issues/1642

However, this small triangle does not look like a proper indicator that there is a selection. But it's a different issue.

![Screenshot_20231220-074603_CoopCycle](https://github.com/coopcycle/coopcycle-app/assets/70273239/2b03f250-5c67-41df-82f2-69e946f9046f)
