### ISSUE TITLE
Dark Mode Text Issues - shop interface

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-app#1682]
- [ ] address field (after clicking the + button to make a new delivery)
- [ ] address field in the delivery creation page (page after inputting the address)
- [ ] phone number field in same page
- [ ] name field in same page
- [ ] comments field in the same page

![telegram-cloud-photo-size-4-5819199731803471745-y](https://github.com/coopcycle/coopcycle-app/assets/77277854/9809b186-dfb2-4c06-a8c9-2cd3dbb82499)

![telegram-cloud-photo-size-4-5819199731803471746-y](https://github.com/coopcycle/coopcycle-app/assets/77277854/304c4a04-1de6-4a7d-a1de-88a1e1870a77)

**Comment by vladimir-8** [comment]
- [x] address field (after clicking the + button to make a new delivery); already fixed

![Screenshot_1705605840](https://github.com/coopcycle/coopcycle-app/assets/70273239/404f363f-25d7-48cc-9dbe-6beceffbdfbd)

Will be fixed in https://github.com/coopcycle/coopcycle-app/pull/1687:

- [x] address field in the delivery creation page (page after inputting the address)
- [x] phone number field in same page
- [x] name field in same page
- [x] comments field in the same page

![Screenshot_1705605859](https://github.com/coopcycle/coopcycle-app/assets/70273239/264f4624-073d-4a4f-86b1-1797ecf98c9a)
