### ISSUE TITLE
settting icon is not visible in the light mode (on restaurant interface)

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-app#1739]
New app loose the stetting icon on clair mode vs dark mode (on restaurant interface)

[Slack Message](https://coopcycle.slack.com/archives/C4UT4DGQ3/p1712175675597619?thread_ts=1712175675.597619&cid=C4UT4DGQ3)

**Comment by v-lozko** [comment]
is it possible to have this assigned to me? I would like to work on it

**Comment by v-lozko** [comment]
I dont have access to that workspace, is it possible to share the message with me just so I have a bit more clarity on the issue.

**Comment by Paul-Eraman-CoopCycle** [comment]
yeah totally!

"New app loose the stetting icon on clair mode vs dark mode (on restaurant interface)"
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/3193c784-04b5-4e1e-8aec-7647a828f4bb)
![image](https://github.com/coopcycle/coopcycle-app/assets/77277854/f46f0fe4-32f8-4041-a4d5-f9db3f98d8fd)

"standby mode too (it is just hidden bescause no contrast)"

that said, i see that one of the team mentioned that they think it is fixed by the fix we deployed the other day. tomorrow ill check on an android device and respond here if it is fixed or not.

**Comment by Paul-Eraman-CoopCycle** [comment]
So it looks like this issue is fixed, but i have been told we have the same issue with the restaurant profile here

https://github.com/coopcycle/coopcycle-app/issues/1741

Want to take a crack at it @v-lozko ? Ill assign it to you if so

**Comment by Paul-Eraman-CoopCycle** [comment]
can you comment in that issue? i tried to assign it to you but you dont appear in the list

**Comment by vladimir-8** [comment]
That's fixed
