### ISSUE TITLE
Canceled orders still appear on restaurant tablets unless you hard refresh the app

### ISSUE THREAD

**Issue by Srywards** [coopcycle/coopcycle-app#1853]
**Describe the bug**
Canceled orders still appear on restaurant tablets unless you hard refresh the app

**To Reproduce**
Cancel an order made on Monday (for example but all day is included) evening but which fell the next day at noon

**Expected behavior**
Orders must be appear canceled for the restaurant without hard refresh the app

**Comment by Atala** [comment]
Tested OK in good conditions (local setup)

**Comment by AdrienSICKLO** [comment]
Dispatchers here are quite doubtful about the network theory... We'll keep investigating but looks like a pattern.
Why would orders go from New to Accepted to Finished when the rider drops it, but canceled would not go to canceled?

**Comment by Paul-Eraman-CoopCycle** [comment]
There is a different path for cancellation than other actions

There is an issue about that by @Atala  that i can find when I'm not on my phone that would probably fix any issues happening with this

Either way, the tasks should update, just not exactly the same second

**Comment by Atala** [comment]
hello

the code to handle order update changes is definitely the same [ref](https://github.com/coopcycle/coopcycle-app/blob/master/src/redux/Restaurant/reducers.js#L539)

i think your dispatcher have a confirmation biases because the order not showing as cancelled for the restaurant is the most painful one.
if i am not wrong
new -> accepted is done by the restaurant itself
accepted -> finished restaurant don't really care

so now i have tested it alright locally and tested it alright with 3 different devices at glasgow burger (sunmi 2vs, sunmi, my phone). i saw the cancellation happen.

what i did test not OK on wattignies network is leaving the network, joining it again and not see a new order popup.

so i would say 95.7% sure it is a network issue until proven wrong.

we know for sure that the fix should be [this](https://github.com/coopcycle/coopcycle-ops/issues/78) = resend messages when the connection was cut. but we are not there yet.

BUT

I have another potential fix and i am planning to do it just for you extra because i know it is a pain for you. i ll let you know.

**Comment by Atala** [comment]
(the issue speaks more precisely of an order that was made for the next day, that might be a different issue but I dont think so as wellà

**Comment by Paul-Eraman-CoopCycle** [comment]
then can we close this and track in #78?
