### ISSUE TITLE
End tasks without internet connection and sync later

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-app#250]

**Comment by cccchurri** [comment]
Not sure how this is meant, but I like to add with this that I recently had this where I didn't had connection with the first job and with the second delivery noticed. Synced both deliveries and both signatures ended up in one job, the other one had non.

**Comment by GuidoHaagen** [comment]
The goal is that you can end a tasks. Even without internet and coopcycle then syncs once the connection is back.

**Comment by couleurmate** [comment]
An offline mode would be the solution. Basically courier can chose to be live synced or manually pull/push data

**Comment by GuidoHaagen** [comment]
For me there are two different things: 
1. beeing online and working but there is no internet connection (e.g. basement) and you still have the possibility to end tasks. 
2. You are taking a break / not working and you do not want to receive notifications.

**Comment by cccchurri** [comment]
True that, though with the experience delivering for Zalando (I know....) we had this app (forgot the name) where you could be offline and upload the deliveries once connected. We used that to cheat. We were not allowed to start before 18:30 but did. Had the phone offline and went online when finished the tour so all the times would be after 18:30. 
So, I think it would be good to use the time when the task was ended, not the time when the app is connected again. So the proof of delivery is also the time it was delivered!!

**Comment by couleurmate** [comment]
@GuidoHaagen To me offline mode merge those two scenarios. If for whatever reason (connection lost or voluntarily offline) data can't be sent to server, triggering a button active/idle would fetch data. 

So basically, two modes : 
- Online/Active = automatically syncing data
- Offline/Iddle = storing data locally to be pushed

**Comment by GuidoHaagen** [comment]
@couleurmate To me that are not the same things if you can only end tasks with internet connection while beeing Online/Active. e.g. no connection but active

**Comment by alexsegura** [comment]
Some options to deal with this:

- https://pusher.com/tutorials/offline-react-native-part-1
- https://brucelefebvre.com/blog/2018/11/06/react-native-offline-first-db-with-sqlite/
- https://github.com/rgommezz/react-native-offline
- https://hackernoon.com/introducing-redux-offline-offline-first-architecture-for-progressive-web-applications-and-react-68c5167ecfe0

**Comment by alexsegura** [comment]
Ok, I now have a more clear idea of what needs to be done. 

"Real" offline mode, i.e retrying actions once the connection comes back, is hard. 
Let's target this in the long term, but the first thing to do is to save locally the remote data, so that the app can at least work in "read-only" mode (see #348), and hide buttons that cannot be used when the app is offline.

**Comment by GuidoHaagen** [comment]
Sounds good! Will it be possible to finish tasks?

**Comment by alexsegura** [comment]
@GuidoHaagen what I'm saying is that I'd prefer doing this progressively. 2 steps:

1/ Allow opening the app & browsing tasks (loaded previously) without Internet. This would be a great improvement, as now if you close the app & re-open it in a basement without Internet, it doesn't work at all, the app won't even start. In this first version, the "complete" button would be hidden without Internet. 

2/ Allow retrying actions when Internet comes back.

**Comment by ERAMANrepartos** [comment]
Have we done either of these two steps? 
@alexsegura

**Comment by alexsegura** [comment]
@ERAMANrepartos We have done step 1.

**Comment by ERAMANrepartos** [comment]
I believe that the second step is this issue:
https://github.com/coopcycle/coopcycle-app/issues/1492

and we are testing it now, but theoretically it is ready to release!

**Comment by r0xsh** [comment]
As it stands, the changes made in #1492 only prevent the interface from being blocked during upload. The upload is launched in the background ONLY when the task is marked as done or failed.
So there's an extra step to ask the courier when to send the images, but it shouldn't be too complex to add this option.

So I see two different issues here:
- Make file uploading smarter (upload over wifi, retry on connection change, etc.). Because I'm not sure that making it manual is a good idea, the courier may forget to upload them and the photos may be lost or mixed up.
- Having an offline state: https://github.com/coopcycle/coopcycle-app/issues/362

Keeping the application state in offline mode and synchronizing later with the server is clearly an epic. The application architecture has not been designed with this possibility in mind, so major changes need to be made to achieve this result.

**Comment by ERAMANrepartos** [comment]
I understand that there are two issues here, one that us addressed in that other issue. Could we create a new issue explaining only the part not addressed in the other issue and put it in the roadmap?
