### ISSUE TITLE
Geolocalisation : only in task mode

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-app#335]
Geolocalisation must be send only in task mode.
As a courrier with other roles geolocalisation is send also in dispatch , restaurant and customer mode.

**Comment by alexsegura** [comment]
Ok, something is wrong then, it is intended to be like this.

**Comment by alexsegura** [comment]
Since c6855e0b1394de287c8dbf67eb56ea0ee1fe887e, the geolocation tracking should at least be properly stopped when the user logs out, and is not a messenger.

I'm struggling to find how to enable the geolocation tracking only in messenger screens, because of technical details of React Navigation: actually, the "map" screen will stay mounted all the time.

> Coming to React Navigation from the web, you may assume that when user navigates from route A to route B, A will unmount and its componentWillUnmount will be called. You may also expect A will remount again when user comes back to it. While these React lifecycle methods are still valid and are used in React Navigation, their usage differs from the web. This is driven by more complex needs of mobile navigation.

I think a better option would be to add a setting to enable/disable geolocation tracking.

**Comment by Paul-Eraman-CoopCycle** [comment]
not currently planned, closing
