### ISSUE TITLE
In order to have the app in Portuguese as a contributor

### ISSUE THREAD

**Issue by jfoclpf** [coopcycle/coopcycle-app#678]
Hi there
I would like to contribute for the translation of this app to Portuguese
How does it work exactly?

**Comment by alexsegura** [comment]
Hi @jfoclpf 

Thank you for proposing your help. 
You can either translate directly by adding a `pt_PT.json` file in the [`src/i18n/locales`](https://github.com/coopcycle/coopcycle-app/tree/master/src/i18n/locales) folder, or you can use our [translation webapp](https://translate.coopcycle.org/) for this.

**Comment by jfoclpf** [comment]
@alexsegura 
Thanks, could you add Portuguese from Portugal to the translation webpage, such that we could start translating?
Thanks

**Comment by alexsegura** [comment]
You should be able to do it yourself 🙂 
Register on the translation webapp, then on the [list of components](https://translate.coopcycle.org/projects/coopcycle/), when clicking on a component (for example, the [App component](https://translate.coopcycle.org/projects/coopcycle/coopcycle-app/)), you should have a "Start a new translation" button.  
There, you can select the language you want to add.

**Comment by jfoclpf** [comment]
Thanks a lot, done it
I will start the translation asap

**Comment by jfoclpf** [comment]
I am now translating. Just a suggestion: the context of the word should be more precise.

When I simply read the word `submit` I don't know if this is a verb in infinitive, imperative or a noun, and in Portuguese and other languages the translations changes accordingly. Please, when you have time, mainly in expressions with only one word, try to refer if it is:

 - a noun
 - verb in infinitive form
 - verb in imperative form

**Comment by alexsegura** [comment]
> Just a suggestion: the context of the word should be more precise.

I agree it can be hard 😐

Currently, the only thing we have at hand to express some context is the translation key. 
On Weblate it appears as "Context". So, yes, instead of `submit`, something like `buttons.submit` can help more. 

<img width="802" alt="Capture d’écran 2020-07-15 à 19 31 57" src="https://user-images.githubusercontent.com/1162230/87576722-153d6b80-c6d2-11ea-8752-1b6e22b24bc1.png">

There would need to be some manual work on the translations, at least a work of de-duplication, because sometimes we add translations without thinking too much, and it ends up with a LOT of things to translate, and adding more languages will be a nightmare.
