### ISSUE TITLE
Update's notification about Task's status using App as Coursier

### ISSUE THREAD

**Issue by Francine165** [coopcycle/coopcycle-app#860]
**In order to** be coordinated

**As** a Coursier

**I want**  push notifications about tasks' update (new task, task started, task completed, etc.)

**Whereas currently** nothing happen in App

**Additional context**
We plan to work without any 'Dispatcher' on web interface. The Coursiers will be on the field using the App. Each one of us will be able to complete tasks from the dispatch.

**Comment by ERAMANrepartos** [comment]
This is a feature that is very adapted to your use case, and would make the dispatch of all the other instances incredible "noisy" in regards to information overload. Also, this issue is fixed by having a solid communication channel between flying dispatch and riders such as Zello, which you should have to implement anyways. 

For these reasons I'm going to close the issue to do an inability to prioritize the feature.
