### ISSUE TITLE
Order actually moves to "Picked orders" section when a messenger is assigned

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#929]
This code is wrong

https://github.com/coopcycle/coopcycle-app/blob/9c4b9275da9a8c188e3fc1d733b989fcf461f53d/src/redux/Restaurant/selectors.js#L46-L53

**Comment by ERAMANrepartos** [comment]
Is this fixed?

**Comment by vladimir-8** [comment]
I was going to ask about the the same issue

What should be the expected behaviour, should it check `order:picked` event instead?

Also, should we implement "Picked orders" column on the web?

**Comment by Paul-Eraman-CoopCycle** [comment]
When possible the idea is to add "picked orders" to the column on the web and make the "cancelled" column collapsable to make space.

**Comment by vladimir-8** [comment]
I made a quick fix by checking `order:picked` event instead of the `assignedTo` field, but I don't think it's a proper solution, as these events, probably, should not even be exposed in the list of orders. Ideally, we should implement a separate state, something like `order:picked` and rely on it instead
