### ISSUE TITLE
Screen "more info" (phonenumber input aso. just before payment) : unable to close the keyboard on iPhone SE 2020 -> impossible to access the next button

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-app#932]
**Describe the bug**
On this screen :
 - first input "phone" is focused : on the keyboard you can click "OK" to close it
 - second input : unable to close the keyboard -> unable to click the button "next"
 - third input : unable to close the keyboard -> unable to click the button "next"

**Comment by alexsegura** [comment]
It's not possible to add a return key on multiline fields to go to next field, because it's used to go to next line. 
It's working as expected, keyboard can be closed by clicking outside (tested on iPhone SE2020)

https://user-images.githubusercontent.com/1162230/128343999-cd422246-a2bb-48d5-9ed8-e1e7e433e38a.mov
